/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArchitectureSection: typeof import('./components/landing/sections/ArchitectureSection.vue')['default']
    AuthDialog: typeof import('./components/AuthDialog.vue')['default']
    ContactCard: typeof import('./components/contact/ContactCard.vue')['default']
    ContactDialog: typeof import('./components/contact/ContactDialog.vue')['default']
    CreateObservatoryDialog: typeof import('./components/CreateObservatoryDialog.vue')['default']
    DashboardDrawer: typeof import('./components/DashboardDrawer.vue')['default']
    HeroSection: typeof import('./components/landing/sections/HeroSection.vue')['default']
    HowItWorksSection: typeof import('./components/landing/sections/HowItWorksSection.vue')['default']
    IntroductionSection: typeof import('./components/landing/sections/IntroductionSection.vue')['default']
    LandingFooter: typeof import('./components/landing/sections/LandingFooter.vue')['default']
    LogicMapSection: typeof import('./components/landing/sections/LogicMapSection.vue')['default']
    ObservatoryCard: typeof import('./components/dashboard/ObservatoryCard.vue')['default']
    ObservatoryCarousel: typeof import('./components/landing/sections/ObservatoryCarousel.vue')['default']
    ObservatoryCarouselCard: typeof import('./components/landing/sections/ObservatoryCarouselCard.vue')['default']
    ObservatoryDialog: typeof import('./components/dashboard/ObservatoryDialog.vue')['default']
    ObservatoryTables: typeof import('./components/dashboard/ObservatoryTables.vue')['default']
    ReadyToGetStartedSection: typeof import('./components/landing/sections/ReadyToGetStartedSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Separator: typeof import('./components/Separator.vue')['default']
    ServiceAppBar: typeof import('./components/ServiceAppBar.vue')['default']
    StatsSection: typeof import('./components/landing/sections/StatsSection.vue')['default']
    ValueProposition: typeof import('./components/landing/sections/ValueProposition.vue')['default']
  }
}
