/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'Home': RouteRecordInfo<'Home', '/', Record<never, never>, Record<never, never>>,
    'Catalogs': RouteRecordInfo<'Catalogs', '/catalogs', Record<never, never>, Record<never, never>>,
    'CatalogDetails': RouteRecordInfo<'CatalogDetails', '/catalogs/:catalogId', { catalogId: ParamValue<true> }, { catalogId: ParamValue<false> }>,
    'Contact': RouteRecordInfo<'Contact', '/contact', Record<never, never>, Record<never, never>>,
    'Dashboard': RouteRecordInfo<'Dashboard', '/dashboard', Record<never, never>, Record<never, never>>,
    'DataSources': RouteRecordInfo<'DataSources', '/datasources', Record<never, never>, Record<never, never>>,
    'DataSourceDetail': RouteRecordInfo<'DataSourceDetail', '/datasources/:sourceId', { sourceId: ParamValue<true> }, { sourceId: ParamValue<false> }>,
    'Guides': RouteRecordInfo<'Guides', '/guides', Record<never, never>, Record<never, never>>,
    'QueryGuide': RouteRecordInfo<'QueryGuide', '/guides/query', Record<never, never>, Record<never, never>>,
    'Observatories': RouteRecordInfo<'Observatories', '/observatories', Record<never, never>, Record<never, never>>,
    'ObservatoryDetails': RouteRecordInfo<'ObservatoryDetails', '/observatories/:observatory_id', { observatory_id: ParamValue<true> }, { observatory_id: ParamValue<false> }>,
    'Alerta': RouteRecordInfo<'Alerta', '/observatories/alerta', Record<never, never>, Record<never, never>>,
    'Azomalli': RouteRecordInfo<'Azomalli', '/observatories/azomalli', Record<never, never>, Record<never, never>>,
    'IMA': RouteRecordInfo<'IMA', '/observatories/ima', Record<never, never>, Record<never, never>>,
    'Kaexla': RouteRecordInfo<'Kaexla', '/observatories/kaexla', Record<never, never>, Record<never, never>>,
    'Products': RouteRecordInfo<'Products', '/products', Record<never, never>, Record<never, never>>,
    'Charts': RouteRecordInfo<'Charts', '/products/plot', Record<never, never>, Record<never, never>>,
    'Services': RouteRecordInfo<'Services', '/services', Record<never, never>, Record<never, never>>,
    'MictlanX': RouteRecordInfo<'MictlanX', '/services/mictlanx', Record<never, never>, Record<never, never>>,
    'Nez': RouteRecordInfo<'Nez', '/services/nez', Record<never, never>, Record<never, never>>,
    'Xelhua': RouteRecordInfo<'Xelhua', '/services/xelhua', Record<never, never>, Record<never, never>>,
    'Signin': RouteRecordInfo<'Signin', '/signin', Record<never, never>, Record<never, never>>,
    'TasksIndex': RouteRecordInfo<'TasksIndex', '/tasks', Record<never, never>, Record<never, never>>,
    'TaskDetails': RouteRecordInfo<'TaskDetails', '/tasks/:taskId', { taskId: ParamValue<true> }, { taskId: ParamValue<false> }>,
    '/test': RouteRecordInfo<'/test', '/test', Record<never, never>, Record<never, never>>,
    'UsersIndex': RouteRecordInfo<'UsersIndex', '/users', Record<never, never>, Record<never, never>>,
    'UserProfile': RouteRecordInfo<'UserProfile', '/users/profile', Record<never, never>, Record<never, never>>,
    'Settings': RouteRecordInfo<'Settings', '/users/settings', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: 'Home'
      views: never
    }
    'src/pages/catalogs/index.vue': {
      routes: 'Catalogs'
      views: never
    }
    'src/pages/catalogs/[catalogId].vue': {
      routes: 'CatalogDetails'
      views: never
    }
    'src/pages/contact.vue': {
      routes: 'Contact'
      views: never
    }
    'src/pages/dashboard.vue': {
      routes: 'Dashboard'
      views: never
    }
    'src/pages/datasources/index.vue': {
      routes: 'DataSources'
      views: never
    }
    'src/pages/datasources/[sourceId].vue': {
      routes: 'DataSourceDetail'
      views: never
    }
    'src/pages/guides/index.vue': {
      routes: 'Guides'
      views: never
    }
    'src/pages/guides/query.vue': {
      routes: 'QueryGuide'
      views: never
    }
    'src/pages/observatories/index.vue': {
      routes: 'Observatories'
      views: never
    }
    'src/pages/observatories/[observatory_id].vue': {
      routes: 'ObservatoryDetails'
      views: never
    }
    'src/pages/observatories/alerta.vue': {
      routes: 'Alerta'
      views: never
    }
    'src/pages/observatories/azomalli.vue': {
      routes: 'Azomalli'
      views: never
    }
    'src/pages/observatories/ima.vue': {
      routes: 'IMA'
      views: never
    }
    'src/pages/observatories/kaexla.vue': {
      routes: 'Kaexla'
      views: never
    }
    'src/pages/products/index.vue': {
      routes: 'Products'
      views: never
    }
    'src/pages/products/plot.vue': {
      routes: 'Charts'
      views: never
    }
    'src/pages/services/index.vue': {
      routes: 'Services'
      views: never
    }
    'src/pages/services/mictlanx.vue': {
      routes: 'MictlanX'
      views: never
    }
    'src/pages/services/nez.vue': {
      routes: 'Nez'
      views: never
    }
    'src/pages/services/xelhua.vue': {
      routes: 'Xelhua'
      views: never
    }
    'src/pages/signin.vue': {
      routes: 'Signin'
      views: never
    }
    'src/pages/tasks/index.vue': {
      routes: 'TasksIndex'
      views: never
    }
    'src/pages/tasks/[taskId].vue': {
      routes: 'TaskDetails'
      views: never
    }
    'src/pages/test.vue': {
      routes: '/test'
      views: never
    }
    'src/pages/users/index.vue': {
      routes: 'UsersIndex'
      views: never
    }
    'src/pages/users/profile.vue': {
      routes: 'UserProfile'
      views: never
    }
    'src/pages/users/settings.vue': {
      routes: 'Settings'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
